# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.time_zone_setup_infos_api import TimeZoneSetupInfosApi


class TestTimeZoneSetupInfosApi(unittest.TestCase):
    """TimeZoneSetupInfosApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TimeZoneSetupInfosApi()

    def tearDown(self) -> None:
        pass

    def test_get_system_time_zone_setups_by_id_info(self) -> None:
        """Test case for get_system_time_zone_setups_by_id_info

        Get TimeZoneSetupInfos
        """
        pass

    def test_get_system_time_zone_setups_info(self) -> None:
        """Test case for get_system_time_zone_setups_info

        Get List of TimeZoneSetupInfos
        """
        pass

    def test_get_system_time_zone_setups_info_count(self) -> None:
        """Test case for get_system_time_zone_setups_info_count

        Get Count of TimeZoneSetupInfos
        """
        pass


if __name__ == '__main__':
    unittest.main()
