# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from connectwise_psa.models.security_role_setting import SecurityRoleSetting

class TestSecurityRoleSetting(unittest.TestCase):
    """SecurityRoleSetting unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SecurityRoleSetting:
        """Test SecurityRoleSetting
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SecurityRoleSetting`
        """
        model = SecurityRoleSetting()
        if include_optional:
            return SecurityRoleSetting(
                info = {
                    'key' : ''
                    },
                add_level = 'None',
                custom_flag = True,
                delete_level = 'None',
                edit_level = 'None',
                id = 56,
                inquire_level = 'None',
                module_description = '',
                module_function_description = '',
                module_function_identifier = '',
                module_function_name = '',
                module_identifier = '',
                module_name = '',
                my_all_flag = True,
                report_flag = True,
                restrict_flag = True,
                sort_order = 56
            )
        else:
            return SecurityRoleSetting(
        )
        """

    def testSecurityRoleSetting(self):
        """Test SecurityRoleSetting"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
