# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.setup_screens_api import SetupScreensApi


class TestSetupScreensApi(unittest.TestCase):
    """SetupScreensApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SetupScreensApi()

    def tearDown(self) -> None:
        pass

    def test_get_system_setup_screens(self) -> None:
        """Test case for get_system_setup_screens

        Get List of SetupScreen
        """
        pass

    def test_get_system_setup_screens_by_id(self) -> None:
        """Test case for get_system_setup_screens_by_id

        Get SetupScreen
        """
        pass

    def test_get_system_setup_screens_count(self) -> None:
        """Test case for get_system_setup_screens_count

        Get Count of SetupScreen
        """
        pass


if __name__ == '__main__':
    unittest.main()
