# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from connectwise_psa.models.agreement_type import AgreementType

class TestAgreementType(unittest.TestCase):
    """AgreementType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgreementType:
        """Test AgreementType
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgreementType`
        """
        model = AgreementType()
        if include_optional:
            return AgreementType(
                info = {
                    'key' : ''
                    },
                add_all_work_role_exclusions = True,
                add_all_work_type_exclusions = True,
                allow_overruns_flag = True,
                application_cycle = 'Contract2Weeks',
                application_limit = 1.337,
                application_units = 'Amount',
                application_unlimited_flag = True,
                auto_invoice_flag = True,
                bill_amount = 1.337,
                bill_expenses = 'Billable',
                bill_one_time_flag = True,
                bill_products = 'Billable',
                bill_time = 'Billable',
                billable_expense_invoice_flag = True,
                billable_product_invoice_flag = True,
                billable_time_invoice_flag = True,
                billing_cycle = connectwise_psa.models.billing_cycle_reference.BillingCycleReference(
                    _info = {
                        'key' : ''
                        }, 
                    id = 56, 
                    name = '', ),
                billing_terms = connectwise_psa.models.billing_terms_reference.BillingTermsReference(
                    _info = {
                        'key' : ''
                        }, 
                    id = 56, 
                    name = '', ),
                bottom_comment_flag = True,
                carry_over_unused_flag = True,
                charge_to_firm_flag = True,
                comp_hourly_rate = 1.337,
                comp_limit_amount = 1.337,
                copy_work_roles_flag = True,
                copy_work_types_flag = True,
                cover_agreement_expense_flag = True,
                cover_agreement_product_flag = True,
                cover_agreement_time_flag = True,
                cover_sales_tax_flag = True,
                default_flag = True,
                department = connectwise_psa.models.system_department_reference.SystemDepartmentReference(
                    _info = {
                        'key' : ''
                        }, 
                    id = 56, 
                    identifier = '', 
                    name = '', ),
                email_template = connectwise_psa.models.email_template_reference.EmailTemplateReference(
                    _info = {
                        'key' : ''
                        }, 
                    id = 56, 
                    name = '', ),
                employee_comp_not_exceed = 'Billing',
                employee_comp_rate = 'Actual',
                exclusion_work_role_ids = [
                    56
                    ],
                exclusion_work_type_ids = [
                    56
                    ],
                expire_when_zero = True,
                expired_days = 56,
                id = 56,
                inactive_flag = True,
                integration_x_ref = '',
                invoice_description = '',
                invoice_pre_suffix = '',
                invoice_prorated_additions_flag = True,
                invoice_template = connectwise_psa.models.invoice_template_reference.InvoiceTemplateReference(
                    _info = {
                        'key' : ''
                        }, 
                    id = 56, 
                    name = '', ),
                invoicing_cycle = 'ContractYear',
                limit = 56,
                location = connectwise_psa.models.system_location_reference.SystemLocationReference(
                    _info = {
                        'key' : ''
                        }, 
                    id = 56, 
                    name = '', ),
                name = '',
                one_time_flag = True,
                pre_payment_flag = True,
                prefix_suffix_option = 'Prefix',
                project_type = connectwise_psa.models.project_type_reference.ProjectTypeReference(
                    _info = {
                        'key' : ''
                        }, 
                    id = 56, 
                    name = '', ),
                prorate_flag = True,
                remove_all_work_role_exclusions = True,
                remove_all_work_type_exclusions = True,
                restrict_department_flag = True,
                restrict_down_payment_flag = True,
                restrict_location_flag = True,
                sla = connectwise_psa.models.sla_reference.SLAReference(
                    _info = {
                        'key' : ''
                        }, 
                    id = 56, 
                    name = '', ),
                taxable_flag = True,
                top_comment_flag = True,
                work_role = connectwise_psa.models.work_role_reference.WorkRoleReference(
                    _info = {
                        'key' : ''
                        }, 
                    id = 56, 
                    name = '', ),
                work_type = connectwise_psa.models.work_type_reference.WorkTypeReference(
                    _info = {
                        'key' : ''
                        }, 
                    id = 56, 
                    name = '', )
            )
        else:
            return AgreementType(
                bill_expenses = 'Billable',
                bill_products = 'Billable',
                bill_time = 'Billable',
                employee_comp_not_exceed = 'Billing',
                employee_comp_rate = 'Actual',
                invoicing_cycle = 'ContractYear',
                name = '',
        )
        """

    def testAgreementType(self):
        """Test AgreementType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
