# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.pricing_schedules_api import PricingSchedulesApi


class TestPricingSchedulesApi(unittest.TestCase):
    """PricingSchedulesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PricingSchedulesApi()

    def tearDown(self) -> None:
        pass

    def test_delete_procurement_pricingschedules_by_id(self) -> None:
        """Test case for delete_procurement_pricingschedules_by_id

        Delete PricingSchedule
        """
        pass

    def test_get_procurement_pricingschedules(self) -> None:
        """Test case for get_procurement_pricingschedules

        Get List of PricingSchedule
        """
        pass

    def test_get_procurement_pricingschedules_by_id(self) -> None:
        """Test case for get_procurement_pricingschedules_by_id

        Get PricingSchedule
        """
        pass

    def test_get_procurement_pricingschedules_count(self) -> None:
        """Test case for get_procurement_pricingschedules_count

        Get Count of PricingSchedule
        """
        pass

    def test_patch_procurement_pricingschedules_by_id(self) -> None:
        """Test case for patch_procurement_pricingschedules_by_id

        Patch PricingSchedule
        """
        pass

    def test_post_procurement_pricingschedules(self) -> None:
        """Test case for post_procurement_pricingschedules

        Post PricingSchedule
        """
        pass

    def test_put_procurement_pricingschedules_by_id(self) -> None:
        """Test case for put_procurement_pricingschedules_by_id

        Put PricingSchedule
        """
        pass


if __name__ == '__main__':
    unittest.main()
