# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.schedule_details_api import ScheduleDetailsApi


class TestScheduleDetailsApi(unittest.TestCase):
    """ScheduleDetailsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ScheduleDetailsApi()

    def tearDown(self) -> None:
        pass

    def test_get_schedule_entries_by_parent_id_details(self) -> None:
        """Test case for get_schedule_entries_by_parent_id_details

        Get List of ScheduleDetail
        """
        pass

    def test_get_schedule_entries_by_parent_id_details_by_id(self) -> None:
        """Test case for get_schedule_entries_by_parent_id_details_by_id

        Get ScheduleDetail
        """
        pass

    def test_get_schedule_entries_by_parent_id_details_count(self) -> None:
        """Test case for get_schedule_entries_by_parent_id_details_count

        Get Count of ScheduleDetail
        """
        pass


if __name__ == '__main__':
    unittest.main()
