# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.management_report_notifications_api import ManagementReportNotificationsApi


class TestManagementReportNotificationsApi(unittest.TestCase):
    """ManagementReportNotificationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ManagementReportNotificationsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_company_companies_by_parent_id_management_report_notifications_by_id(self) -> None:
        """Test case for delete_company_companies_by_parent_id_management_report_notifications_by_id

        Delete ManagementReportNotification
        """
        pass

    def test_delete_company_management_by_parent_id_management_report_notifications_by_id(self) -> None:
        """Test case for delete_company_management_by_parent_id_management_report_notifications_by_id

        Delete ManagementReportNotification
        """
        pass

    def test_get_company_companies_by_parent_id_management_report_notifications(self) -> None:
        """Test case for get_company_companies_by_parent_id_management_report_notifications

        Get List of ManagementReportNotification
        """
        pass

    def test_get_company_companies_by_parent_id_management_report_notifications_by_id(self) -> None:
        """Test case for get_company_companies_by_parent_id_management_report_notifications_by_id

        Get ManagementReportNotification
        """
        pass

    def test_get_company_companies_by_parent_id_management_report_notifications_count(self) -> None:
        """Test case for get_company_companies_by_parent_id_management_report_notifications_count

        Get Count of ManagementReportNotification
        """
        pass

    def test_get_company_management_by_parent_id_management_report_notifications(self) -> None:
        """Test case for get_company_management_by_parent_id_management_report_notifications

        Get List of ManagementReportNotification
        """
        pass

    def test_get_company_management_by_parent_id_management_report_notifications_by_id(self) -> None:
        """Test case for get_company_management_by_parent_id_management_report_notifications_by_id

        Get ManagementReportNotification
        """
        pass

    def test_get_company_management_by_parent_id_management_report_notifications_count(self) -> None:
        """Test case for get_company_management_by_parent_id_management_report_notifications_count

        Get Count of ManagementReportNotification
        """
        pass

    def test_patch_company_companies_by_parent_id_management_report_notifications_by_id(self) -> None:
        """Test case for patch_company_companies_by_parent_id_management_report_notifications_by_id

        Patch ManagementReportNotification
        """
        pass

    def test_patch_company_management_by_parent_id_management_report_notifications_by_id(self) -> None:
        """Test case for patch_company_management_by_parent_id_management_report_notifications_by_id

        Patch ManagementReportNotification
        """
        pass

    def test_post_company_companies_by_parent_id_management_report_notifications(self) -> None:
        """Test case for post_company_companies_by_parent_id_management_report_notifications

        Post ManagementReportNotification
        """
        pass

    def test_post_company_management_by_parent_id_management_report_notifications(self) -> None:
        """Test case for post_company_management_by_parent_id_management_report_notifications

        Post ManagementReportNotification
        """
        pass

    def test_put_company_companies_by_parent_id_management_report_notifications_by_id(self) -> None:
        """Test case for put_company_companies_by_parent_id_management_report_notifications_by_id

        Put ManagementReportNotification
        """
        pass

    def test_put_company_management_by_parent_id_management_report_notifications_by_id(self) -> None:
        """Test case for put_company_management_by_parent_id_management_report_notifications_by_id

        Put ManagementReportNotification
        """
        pass


if __name__ == '__main__':
    unittest.main()
