# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.pricing_details_api import PricingDetailsApi


class TestPricingDetailsApi(unittest.TestCase):
    """PricingDetailsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PricingDetailsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_procurement_pricingschedules_by_parent_id_details_by_id(self) -> None:
        """Test case for delete_procurement_pricingschedules_by_parent_id_details_by_id

        Delete PricingDetail
        """
        pass

    def test_get_procurement_pricingschedules_by_parent_id_details(self) -> None:
        """Test case for get_procurement_pricingschedules_by_parent_id_details

        Get List of PricingDetail
        """
        pass

    def test_get_procurement_pricingschedules_by_parent_id_details_by_id(self) -> None:
        """Test case for get_procurement_pricingschedules_by_parent_id_details_by_id

        Get PricingDetail
        """
        pass

    def test_get_procurement_pricingschedules_by_parent_id_details_count(self) -> None:
        """Test case for get_procurement_pricingschedules_by_parent_id_details_count

        Get Count of PricingDetail
        """
        pass

    def test_patch_procurement_pricingschedules_by_parent_id_details_by_id(self) -> None:
        """Test case for patch_procurement_pricingschedules_by_parent_id_details_by_id

        Patch PricingDetail
        """
        pass

    def test_post_procurement_pricingschedules_by_parent_id_details(self) -> None:
        """Test case for post_procurement_pricingschedules_by_parent_id_details

        Post PricingDetail
        """
        pass

    def test_put_procurement_pricingschedules_by_parent_id_details_by_id(self) -> None:
        """Test case for put_procurement_pricingschedules_by_parent_id_details_by_id

        Put PricingDetail
        """
        pass


if __name__ == '__main__':
    unittest.main()
