# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.campaign_types_api import CampaignTypesApi


class TestCampaignTypesApi(unittest.TestCase):
    """CampaignTypesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CampaignTypesApi()

    def tearDown(self) -> None:
        pass

    def test_delete_marketing_campaigns_types_by_id(self) -> None:
        """Test case for delete_marketing_campaigns_types_by_id

        Delete CampaignType
        """
        pass

    def test_get_marketing_campaigns_types(self) -> None:
        """Test case for get_marketing_campaigns_types

        Get List of CampaignType
        """
        pass

    def test_get_marketing_campaigns_types_by_id(self) -> None:
        """Test case for get_marketing_campaigns_types_by_id

        Get CampaignType
        """
        pass

    def test_get_marketing_campaigns_types_count(self) -> None:
        """Test case for get_marketing_campaigns_types_count

        Get Count of CampaignType
        """
        pass

    def test_patch_marketing_campaigns_types_by_id(self) -> None:
        """Test case for patch_marketing_campaigns_types_by_id

        Patch CampaignType
        """
        pass

    def test_post_marketing_campaigns_types(self) -> None:
        """Test case for post_marketing_campaigns_types

        Post CampaignType
        """
        pass

    def test_put_marketing_campaigns_types_by_id(self) -> None:
        """Test case for put_marketing_campaigns_types_by_id

        Put CampaignType
        """
        pass


if __name__ == '__main__':
    unittest.main()
