# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.project_template_tickets_api import ProjectTemplateTicketsApi


class TestProjectTemplateTicketsApi(unittest.TestCase):
    """ProjectTemplateTicketsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectTemplateTicketsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_project_project_templates_by_parent_id_project_template_tickets_by_id(self) -> None:
        """Test case for delete_project_project_templates_by_parent_id_project_template_tickets_by_id

        Delete ProjectTemplateTickets
        """
        pass

    def test_get_project_project_templates_by_parent_id_project_template_tickets(self) -> None:
        """Test case for get_project_project_templates_by_parent_id_project_template_tickets

        Get List of ProjectTemplateTickets
        """
        pass

    def test_get_project_project_templates_by_parent_id_project_template_tickets_by_id(self) -> None:
        """Test case for get_project_project_templates_by_parent_id_project_template_tickets_by_id

        Get ProjectTemplateTickets
        """
        pass

    def test_get_project_project_templates_by_parent_id_project_template_tickets_count(self) -> None:
        """Test case for get_project_project_templates_by_parent_id_project_template_tickets_count

        Get Count of ProjectTemplateTickets
        """
        pass

    def test_patch_project_project_templates_by_parent_id_project_template_tickets_by_id(self) -> None:
        """Test case for patch_project_project_templates_by_parent_id_project_template_tickets_by_id

        Patch ProjectTemplateTickets
        """
        pass

    def test_post_project_project_templates_by_parent_id_project_template_tickets(self) -> None:
        """Test case for post_project_project_templates_by_parent_id_project_template_tickets

        Post ProjectTemplateTickets
        """
        pass

    def test_put_project_project_templates_by_parent_id_project_template_tickets_by_id(self) -> None:
        """Test case for put_project_project_templates_by_parent_id_project_template_tickets_by_id

        Put ProjectTemplateTickets
        """
        pass


if __name__ == '__main__':
    unittest.main()
