# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.agreement_work_role_exclusions_api import AgreementWorkRoleExclusionsApi


class TestAgreementWorkRoleExclusionsApi(unittest.TestCase):
    """AgreementWorkRoleExclusionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AgreementWorkRoleExclusionsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_finance_agreements_by_parent_id_work_role_exclusions_by_id(self) -> None:
        """Test case for delete_finance_agreements_by_parent_id_work_role_exclusions_by_id

        Delete AgreementWorkRoleExclusion
        """
        pass

    def test_get_finance_agreements_by_parent_id_work_role_exclusions(self) -> None:
        """Test case for get_finance_agreements_by_parent_id_work_role_exclusions

        Get List of AgreementWorkRoleExclusion
        """
        pass

    def test_get_finance_agreements_by_parent_id_work_role_exclusions_count(self) -> None:
        """Test case for get_finance_agreements_by_parent_id_work_role_exclusions_count

        Get Count of AgreementWorkRoleExclusion
        """
        pass

    def test_post_finance_agreements_by_parent_id_work_role_exclusions(self) -> None:
        """Test case for post_finance_agreements_by_parent_id_work_role_exclusions

        Post AgreementWorkRoleExclusion
        """
        pass


if __name__ == '__main__':
    unittest.main()
