# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.member_personas_api import MemberPersonasApi


class TestMemberPersonasApi(unittest.TestCase):
    """MemberPersonasApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MemberPersonasApi()

    def tearDown(self) -> None:
        pass

    def test_delete_system_members_by_parent_id_personas_by_id(self) -> None:
        """Test case for delete_system_members_by_parent_id_personas_by_id

        Delete MemberPersona
        """
        pass

    def test_get_system_members_by_parent_id_personas(self) -> None:
        """Test case for get_system_members_by_parent_id_personas

        Get List of MemberPersona
        """
        pass

    def test_get_system_members_by_parent_id_personas_by_id(self) -> None:
        """Test case for get_system_members_by_parent_id_personas_by_id

        Get MemberPersona
        """
        pass

    def test_get_system_members_by_parent_id_personas_count(self) -> None:
        """Test case for get_system_members_by_parent_id_personas_count

        Get Count of MemberPersona
        """
        pass

    def test_patch_system_members_by_parent_id_personas_by_id(self) -> None:
        """Test case for patch_system_members_by_parent_id_personas_by_id

        Patch MemberPersona
        """
        pass

    def test_post_system_members_by_parent_id_personas(self) -> None:
        """Test case for post_system_members_by_parent_id_personas

        Post MemberPersona
        """
        pass

    def test_put_system_members_by_parent_id_personas_by_id(self) -> None:
        """Test case for put_system_members_by_parent_id_personas_by_id

        Put MemberPersona
        """
        pass


if __name__ == '__main__':
    unittest.main()
