# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from connectwise_psa.models.gl_export_expense_offset import GLExportExpenseOffset

class TestGLExportExpenseOffset(unittest.TestCase):
    """GLExportExpenseOffset unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GLExportExpenseOffset:
        """Test GLExportExpenseOffset
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GLExportExpenseOffset`
        """
        model = GLExportExpenseOffset()
        if include_optional:
            return GLExportExpenseOffset(
                account_number = '',
                description = '',
                document_date = '',
                document_type = '',
                gl_class = '',
                gl_type_id = '',
                id = 56,
                member = connectwise_psa.models.member_reference.MemberReference(
                    _info = {
                        'key' : ''
                        }, 
                    id = 56, 
                    identifier = '', 
                    name = '', ),
                memo = '',
                total = 1.337
            )
        else:
            return GLExportExpenseOffset(
        )
        """

    def testGLExportExpenseOffset(self):
        """Test GLExportExpenseOffset"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
