# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.member_notification_settings_api import MemberNotificationSettingsApi


class TestMemberNotificationSettingsApi(unittest.TestCase):
    """MemberNotificationSettingsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MemberNotificationSettingsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_system_members_by_parent_id_notification_settings_by_id(self) -> None:
        """Test case for delete_system_members_by_parent_id_notification_settings_by_id

        Delete MemberNotificationSetting
        """
        pass

    def test_get_system_members_by_parent_id_notification_settings(self) -> None:
        """Test case for get_system_members_by_parent_id_notification_settings

        Get List of MemberNotificationSetting
        """
        pass

    def test_get_system_members_by_parent_id_notification_settings_by_id(self) -> None:
        """Test case for get_system_members_by_parent_id_notification_settings_by_id

        Get MemberNotificationSetting
        """
        pass

    def test_get_system_members_by_parent_id_notification_settings_count(self) -> None:
        """Test case for get_system_members_by_parent_id_notification_settings_count

        Get Count of MemberNotificationSetting
        """
        pass

    def test_patch_system_members_by_parent_id_notification_settings_by_id(self) -> None:
        """Test case for patch_system_members_by_parent_id_notification_settings_by_id

        Patch MemberNotificationSetting
        """
        pass

    def test_post_system_members_by_parent_id_notification_settings(self) -> None:
        """Test case for post_system_members_by_parent_id_notification_settings

        Post MemberNotificationSetting
        """
        pass

    def test_put_system_members_by_parent_id_notification_settings_by_id(self) -> None:
        """Test case for put_system_members_by_parent_id_notification_settings_by_id

        Put MemberNotificationSetting
        """
        pass


if __name__ == '__main__':
    unittest.main()
