# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.company_market_description_api import CompanyMarketDescriptionApi


class TestCompanyMarketDescriptionApi(unittest.TestCase):
    """CompanyMarketDescriptionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CompanyMarketDescriptionApi()

    def tearDown(self) -> None:
        pass

    def test_delete_company_market_descriptions_by_id(self) -> None:
        """Test case for delete_company_market_descriptions_by_id

        Delete MarketDescription
        """
        pass

    def test_get_company_market_descriptions(self) -> None:
        """Test case for get_company_market_descriptions

        Get List of MarketDescription
        """
        pass

    def test_get_company_market_descriptions_by_id(self) -> None:
        """Test case for get_company_market_descriptions_by_id

        Get MarketDescription
        """
        pass

    def test_get_company_market_descriptions_by_id_usages(self) -> None:
        """Test case for get_company_market_descriptions_by_id_usages

        Get List of Usage Count
        """
        pass

    def test_get_company_market_descriptions_by_id_usages_list(self) -> None:
        """Test case for get_company_market_descriptions_by_id_usages_list

        Get List of Usage
        """
        pass

    def test_get_company_market_descriptions_count(self) -> None:
        """Test case for get_company_market_descriptions_count

        Get Count of MarketDescription
        """
        pass

    def test_patch_company_market_descriptions_by_id(self) -> None:
        """Test case for patch_company_market_descriptions_by_id

        Patch MarketDescription
        """
        pass

    def test_post_company_market_descriptions(self) -> None:
        """Test case for post_company_market_descriptions

        Post MarketDescription
        """
        pass

    def test_put_company_market_descriptions_by_id(self) -> None:
        """Test case for put_company_market_descriptions_by_id

        Put MarketDescription
        """
        pass


if __name__ == '__main__':
    unittest.main()
