# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.menu_entries_api import MenuEntriesApi


class TestMenuEntriesApi(unittest.TestCase):
    """MenuEntriesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MenuEntriesApi()

    def tearDown(self) -> None:
        pass

    def test_delete_system_menuentries_by_id(self) -> None:
        """Test case for delete_system_menuentries_by_id

        Delete MenuEntry
        """
        pass

    def test_get_system_menuentries(self) -> None:
        """Test case for get_system_menuentries

        Get List of MenuEntry
        """
        pass

    def test_get_system_menuentries_by_id(self) -> None:
        """Test case for get_system_menuentries_by_id

        Get MenuEntry
        """
        pass

    def test_get_system_menuentries_by_id_image(self) -> None:
        """Test case for get_system_menuentries_by_id_image

        Get MenuEntry
        """
        pass

    def test_get_system_menuentries_count(self) -> None:
        """Test case for get_system_menuentries_count

        Get Count of MenuEntry
        """
        pass

    def test_patch_system_menuentries_by_id(self) -> None:
        """Test case for patch_system_menuentries_by_id

        Patch MenuEntry
        """
        pass

    def test_post_system_menuentries(self) -> None:
        """Test case for post_system_menuentries

        Post MenuEntry
        """
        pass

    def test_post_system_menuentries_by_id_image(self) -> None:
        """Test case for post_system_menuentries_by_id_image

        Post MenuEntry
        """
        pass

    def test_put_system_menuentries_by_id(self) -> None:
        """Test case for put_system_menuentries_by_id

        Put MenuEntry
        """
        pass


if __name__ == '__main__':
    unittest.main()
