# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.currency_codes_api import CurrencyCodesApi


class TestCurrencyCodesApi(unittest.TestCase):
    """CurrencyCodesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CurrencyCodesApi()

    def tearDown(self) -> None:
        pass

    def test_get_finance_info_currency_codes(self) -> None:
        """Test case for get_finance_info_currency_codes

        Get List of CurrencyCode
        """
        pass

    def test_get_finance_info_currency_codes_by_id(self) -> None:
        """Test case for get_finance_info_currency_codes_by_id

        Get CurrencyCode
        """
        pass

    def test_get_finance_info_currency_codes_count(self) -> None:
        """Test case for get_finance_info_currency_codes_count

        Get Count of CurrencyCode
        """
        pass


if __name__ == '__main__':
    unittest.main()
