# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from connectwise_psa.models.time_accrual import TimeAccrual

class TestTimeAccrual(unittest.TestCase):
    """TimeAccrual unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TimeAccrual:
        """Test TimeAccrual
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TimeAccrual`
        """
        model = TimeAccrual()
        if include_optional:
            return TimeAccrual(
                info = {
                    'key' : ''
                    },
                holiday_available_type = 'AnniversaryYear',
                holiday_carryover_allowed_flag = True,
                holiday_carryover_limit = 1.337,
                holiday_flag = True,
                id = 56,
                location = connectwise_psa.models.system_location_reference.SystemLocationReference(
                    _info = {
                        'key' : ''
                        }, 
                    id = 56, 
                    name = '', ),
                pto_available_type = 'AnniversaryYear',
                pto_carryover_allowed_flag = True,
                pto_carryover_limit = 1.337,
                pto_flag = True,
                sick_available_type = 'AnniversaryYear',
                sick_carryover_allowed_flag = True,
                sick_carryover_limit = 1.337,
                sick_flag = True,
                vacation_available_type = 'AnniversaryYear',
                vacation_carryover_allowed_flag = True,
                vacation_carryover_limit = 1.337,
                vacation_flag = True
            )
        else:
            return TimeAccrual(
        )
        """

    def testTimeAccrual(self):
        """Test TimeAccrual"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
