# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.inventory_on_hands_api import InventoryOnHandsApi


class TestInventoryOnHandsApi(unittest.TestCase):
    """InventoryOnHandsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InventoryOnHandsApi()

    def tearDown(self) -> None:
        pass

    def test_get_procurement_warehouse_bins_by_parent_id_inventory_on_hand(self) -> None:
        """Test case for get_procurement_warehouse_bins_by_parent_id_inventory_on_hand

        Get List of InventoryOnHand
        """
        pass

    def test_get_procurement_warehouse_bins_by_parent_id_inventory_on_hand_by_id(self) -> None:
        """Test case for get_procurement_warehouse_bins_by_parent_id_inventory_on_hand_by_id

        Get InventoryOnHand
        """
        pass

    def test_get_procurement_warehouse_bins_by_parent_id_inventory_on_hand_count(self) -> None:
        """Test case for get_procurement_warehouse_bins_by_parent_id_inventory_on_hand_count

        Get Count of InventoryOnHand
        """
        pass


if __name__ == '__main__':
    unittest.main()
