# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.board_infos_api import BoardInfosApi


class TestBoardInfosApi(unittest.TestCase):
    """BoardInfosApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BoardInfosApi()

    def tearDown(self) -> None:
        pass

    def test_get_service_info_boards(self) -> None:
        """Test case for get_service_info_boards

        Get List of BoardInfo
        """
        pass

    def test_get_service_info_boards_by_id(self) -> None:
        """Test case for get_service_info_boards_by_id

        Get BoardInfo
        """
        pass

    def test_get_service_info_boards_count(self) -> None:
        """Test case for get_service_info_boards_count

        Get Count of BoardInfo
        """
        pass


if __name__ == '__main__':
    unittest.main()
