# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.orders_api import OrdersApi


class TestOrdersApi(unittest.TestCase):
    """OrdersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrdersApi()

    def tearDown(self) -> None:
        pass

    def test_delete_sales_orders_by_id(self) -> None:
        """Test case for delete_sales_orders_by_id

        Delete Order
        """
        pass

    def test_get_sales_orders(self) -> None:
        """Test case for get_sales_orders

        Get List of Order
        """
        pass

    def test_get_sales_orders_by_id(self) -> None:
        """Test case for get_sales_orders_by_id

        Get Order
        """
        pass

    def test_get_sales_orders_count(self) -> None:
        """Test case for get_sales_orders_count

        Get Count of Order
        """
        pass

    def test_patch_sales_orders_by_id(self) -> None:
        """Test case for patch_sales_orders_by_id

        Patch Order
        """
        pass

    def test_post_sales_orders(self) -> None:
        """Test case for post_sales_orders

        Post List of Order
        """
        pass

    def test_post_sales_orders_by_id_convert_to_service_ticket(self) -> None:
        """Test case for post_sales_orders_by_id_convert_to_service_ticket

        Post Ticket
        """
        pass

    def test_put_sales_orders_by_id(self) -> None:
        """Test case for put_sales_orders_by_id

        Put Order
        """
        pass


if __name__ == '__main__':
    unittest.main()
