# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from connectwise_psa.models.rma_status_email_template import RmaStatusEmailTemplate

class TestRmaStatusEmailTemplate(unittest.TestCase):
    """RmaStatusEmailTemplate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RmaStatusEmailTemplate:
        """Test RmaStatusEmailTemplate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RmaStatusEmailTemplate`
        """
        model = RmaStatusEmailTemplate()
        if include_optional:
            return RmaStatusEmailTemplate(
                info = {
                    'key' : ''
                    },
                body = '',
                copy_sender_flag = True,
                email_address = '',
                first_name = '',
                id = 56,
                last_name = '',
                status = connectwise_psa.models.rma_status_reference.RmaStatusReference(
                    _info = {
                        'key' : ''
                        }, 
                    id = 56, 
                    name = '', ),
                subject = '',
                use_sender_flag = True
            )
        else:
            return RmaStatusEmailTemplate(
                body = '',
                subject = '',
        )
        """

    def testRmaStatusEmailTemplate(self):
        """Test RmaStatusEmailTemplate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
