# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from connectwise_psa.models.history_entry import HistoryEntry

class TestHistoryEntry(unittest.TestCase):
    """HistoryEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HistoryEntry:
        """Test HistoryEntry
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HistoryEntry`
        """
        model = HistoryEntry()
        if include_optional:
            return HistoryEntry(
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                history_type = 'LastLogin',
                member_id = '',
                member_name = '',
                time_zone_offset_display = ''
            )
        else:
            return HistoryEntry(
        )
        """

    def testHistoryEntry(self):
        """Test HistoryEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
