# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from connectwise_psa.models.m365_contact import M365Contact

class TestM365Contact(unittest.TestCase):
    """M365Contact unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> M365Contact:
        """Test M365Contact
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `M365Contact`
        """
        model = M365Contact()
        if include_optional:
            return M365Contact(
                info = {
                    'key' : ''
                    },
                assigned_licenses = '',
                contact_rec_id = 56,
                department = '',
                directory_roles = '',
                display_name = '',
                employee_type = '',
                groups = '',
                id = 56,
                m365_contact_id = '',
                manager_id = '',
                proxy_addresses = '',
                proxy_addresses_plain = '',
                tenant_id = '',
                user_principal_name = ''
            )
        else:
            return M365Contact(
        )
        """

    def testM365Contact(self):
        """Test M365Contact"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
