# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.accounting_unposted_invoices_api import AccountingUnpostedInvoicesApi


class TestAccountingUnpostedInvoicesApi(unittest.TestCase):
    """AccountingUnpostedInvoicesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountingUnpostedInvoicesApi()

    def tearDown(self) -> None:
        pass

    def test_get_finance_accounting_unpostedinvoices(self) -> None:
        """Test case for get_finance_accounting_unpostedinvoices

        Get List of UnpostedInvoice
        """
        pass

    def test_get_finance_accounting_unpostedinvoices_by_id(self) -> None:
        """Test case for get_finance_accounting_unpostedinvoices_by_id

        Get UnpostedInvoice
        """
        pass

    def test_get_finance_accounting_unpostedinvoices_count(self) -> None:
        """Test case for get_finance_accounting_unpostedinvoices_count

        Get Count of UnpostedInvoice
        """
        pass


if __name__ == '__main__':
    unittest.main()
