# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.sales_team_members_api import SalesTeamMembersApi


class TestSalesTeamMembersApi(unittest.TestCase):
    """SalesTeamMembersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SalesTeamMembersApi()

    def tearDown(self) -> None:
        pass

    def test_delete_sales_sales_teams_by_parent_id_members_by_id(self) -> None:
        """Test case for delete_sales_sales_teams_by_parent_id_members_by_id

        Delete SalesTeamMember
        """
        pass

    def test_get_sales_sales_teams_by_parent_id_members(self) -> None:
        """Test case for get_sales_sales_teams_by_parent_id_members

        Get List of SalesTeamMember
        """
        pass

    def test_get_sales_sales_teams_by_parent_id_members_by_id(self) -> None:
        """Test case for get_sales_sales_teams_by_parent_id_members_by_id

        Get SalesTeamMember
        """
        pass

    def test_get_sales_sales_teams_by_parent_id_members_count(self) -> None:
        """Test case for get_sales_sales_teams_by_parent_id_members_count

        Get Count of SalesTeamMember
        """
        pass

    def test_patch_sales_sales_teams_by_parent_id_members_by_id(self) -> None:
        """Test case for patch_sales_sales_teams_by_parent_id_members_by_id

        Patch SalesTeamMember
        """
        pass

    def test_post_sales_sales_teams_by_parent_id_members(self) -> None:
        """Test case for post_sales_sales_teams_by_parent_id_members

        Post SalesTeamMember
        """
        pass

    def test_put_sales_sales_teams_by_parent_id_members_by_id(self) -> None:
        """Test case for put_sales_sales_teams_by_parent_id_members_by_id

        Put SalesTeamMember
        """
        pass


if __name__ == '__main__':
    unittest.main()
