# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from connectwise_psa.models.wise_pay_payment import WisePayPayment

class TestWisePayPayment(unittest.TestCase):
    """WisePayPayment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WisePayPayment:
        """Test WisePayPayment
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WisePayPayment`
        """
        model = WisePayPayment()
        if include_optional:
            return WisePayPayment(
                batch_payment = connectwise_psa.models.wise_pay_batch_payment.WisePayBatchPayment(
                    amount = 1.337, 
                    wise_pay_href = '', ),
                fee_invoice = connectwise_psa.models.wise_pay_fee_invoice.WisePayFeeInvoice(
                    amount = 1.337, 
                    id = 56, 
                    invoice_href = '', 
                    invoice_number = '', ),
                payment_date_utc = '',
                wise_pay_reference = ''
            )
        else:
            return WisePayPayment(
        )
        """

    def testWisePayPayment(self):
        """Test WisePayPayment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
