# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.configuration_type_question_value_infos_api import ConfigurationTypeQuestionValueInfosApi


class TestConfigurationTypeQuestionValueInfosApi(unittest.TestCase):
    """ConfigurationTypeQuestionValueInfosApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConfigurationTypeQuestionValueInfosApi()

    def tearDown(self) -> None:
        pass

    def test_get_configurations_types_by_grandparent_id_questions_by_parent_id_values_by_id_info(self) -> None:
        """Test case for get_configurations_types_by_grandparent_id_questions_by_parent_id_values_by_id_info

        Get ConfigurationTypeQuestionValueInfo
        """
        pass

    def test_get_configurations_types_by_grandparent_id_questions_by_parent_id_values_info(self) -> None:
        """Test case for get_configurations_types_by_grandparent_id_questions_by_parent_id_values_info

        Get ConfigurationTypeQuestionValueInfo
        """
        pass

    def test_get_configurations_types_by_grandparent_id_questions_by_parent_id_values_info_count(self) -> None:
        """Test case for get_configurations_types_by_grandparent_id_questions_by_parent_id_values_info_count

        Get Count of ConfigurationTypeQuestionValueInfos
        """
        pass


if __name__ == '__main__':
    unittest.main()
