# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from connectwise_psa.models.other import Other

class TestOther(unittest.TestCase):
    """Other unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Other:
        """Test Other
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Other`
        """
        model = Other()
        if include_optional:
            return Other(
                info = {
                    'key' : ''
                    },
                contact_sync = 'FL',
                default_address_format = connectwise_psa.models.address_format_reference.AddressFormatReference(
                    _info = {
                        'key' : ''
                        }, 
                    id = 56, 
                    name = '', ),
                default_calendar = connectwise_psa.models.calendar_reference.CalendarReference(
                    _info = {
                        'key' : ''
                        }, 
                    id = 56, 
                    name = '', ),
                default_from_address = '',
                default_ldap = connectwise_psa.models.ldap_configuration_reference.LdapConfigurationReference(
                    _info = {
                        'key' : ''
                        }, 
                    id = 56, 
                    name = '', 
                    server = '', ),
                disable_z_admin_login_flag = True,
                id = 56,
                include_portal_link_flag = True,
                locale = connectwise_psa.models.locale_reference.LocaleReference(
                    _info = {
                        'key' : ''
                        }, 
                    id = 56, 
                    name = '', ),
                logo_path = '',
                portal_url_override = '',
                server_time_zone = connectwise_psa.models.time_zone_setup_reference.TimeZoneSetupReference(
                    _info = {
                        'key' : ''
                        }, 
                    id = 56, 
                    name = '', ),
                site_url = '',
                sync_leads_flag = True,
                update_member_time_zones_flag = True,
                use_expanded_format_activity_flag = True,
                use_expanded_format_time_flag = True,
                use_ssl_flag = True
            )
        else:
            return Other(
                default_from_address = '',
                portal_url_override = '',
                site_url = '',
        )
        """

    def testOther(self):
        """Test Other"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
