# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from connectwise_psa.models.menu_entry import MenuEntry

class TestMenuEntry(unittest.TestCase):
    """MenuEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MenuEntry:
        """Test MenuEntry
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MenuEntry`
        """
        model = MenuEntry()
        if include_optional:
            return MenuEntry(
                info = {
                    'key' : ''
                    },
                add_all_locations = True,
                caption = '',
                client_id = '',
                id = 56,
                large_menu_icon_id = 56,
                link = '',
                location_ids = [
                    56
                    ],
                menu_location = connectwise_psa.models.menu_location_reference.MenuLocationReference(
                    _info = {
                        'key' : ''
                        }, 
                    id = 56, 
                    name = '', ),
                new_window_flag = True,
                origin = '',
                remove_all_locations = True,
                small_menu_icon_id = 56
            )
        else:
            return MenuEntry(
                caption = '',
                link = '',
                new_window_flag = True,
        )
        """

    def testMenuEntry(self):
        """Test MenuEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
