# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.purchase_order_status_email_templates_api import PurchaseOrderStatusEmailTemplatesApi


class TestPurchaseOrderStatusEmailTemplatesApi(unittest.TestCase):
    """PurchaseOrderStatusEmailTemplatesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PurchaseOrderStatusEmailTemplatesApi()

    def tearDown(self) -> None:
        pass

    def test_delete_procurement_purchaseorderstatuses_by_parent_id_emailtemplates_by_id(self) -> None:
        """Test case for delete_procurement_purchaseorderstatuses_by_parent_id_emailtemplates_by_id

        Delete PurchaseOrderStatusEmailTemplate
        """
        pass

    def test_get_procurement_purchaseorderstatuses_by_parent_id_emailtemplates(self) -> None:
        """Test case for get_procurement_purchaseorderstatuses_by_parent_id_emailtemplates

        Get List of PurchaseOrderStatusEmailTemplate
        """
        pass

    def test_get_procurement_purchaseorderstatuses_by_parent_id_emailtemplates_by_id(self) -> None:
        """Test case for get_procurement_purchaseorderstatuses_by_parent_id_emailtemplates_by_id

        Get PurchaseOrderStatusEmailTemplate
        """
        pass

    def test_get_procurement_purchaseorderstatuses_by_parent_id_emailtemplates_count(self) -> None:
        """Test case for get_procurement_purchaseorderstatuses_by_parent_id_emailtemplates_count

        Get Count of PurchaseOrderStatusEmailTemplate
        """
        pass

    def test_patch_procurement_purchaseorderstatuses_by_parent_id_emailtemplates_by_id(self) -> None:
        """Test case for patch_procurement_purchaseorderstatuses_by_parent_id_emailtemplates_by_id

        Patch PurchaseOrderStatusEmailTemplate
        """
        pass

    def test_post_procurement_purchaseorderstatuses_by_parent_id_emailtemplates(self) -> None:
        """Test case for post_procurement_purchaseorderstatuses_by_parent_id_emailtemplates

        Post PurchaseOrderStatusEmailTemplate
        """
        pass

    def test_put_procurement_purchaseorderstatuses_by_parent_id_emailtemplates_by_id(self) -> None:
        """Test case for put_procurement_purchaseorderstatuses_by_parent_id_emailtemplates_by_id

        Put PurchaseOrderStatusEmailTemplate
        """
        pass


if __name__ == '__main__':
    unittest.main()
