# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.service_survey_questions_api import ServiceSurveyQuestionsApi


class TestServiceSurveyQuestionsApi(unittest.TestCase):
    """ServiceSurveyQuestionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServiceSurveyQuestionsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_service_surveys_by_parent_id_questions_by_id(self) -> None:
        """Test case for delete_service_surveys_by_parent_id_questions_by_id

        Delete ServiceSurveyQuestion
        """
        pass

    def test_get_service_surveys_by_parent_id_questions(self) -> None:
        """Test case for get_service_surveys_by_parent_id_questions

        Get List of ServiceSurveyQuestion
        """
        pass

    def test_get_service_surveys_by_parent_id_questions_by_id(self) -> None:
        """Test case for get_service_surveys_by_parent_id_questions_by_id

        Get ServiceSurveyQuestion
        """
        pass

    def test_get_service_surveys_by_parent_id_questions_count(self) -> None:
        """Test case for get_service_surveys_by_parent_id_questions_count

        Get Count of ServiceSurveyQuestion
        """
        pass

    def test_patch_service_surveys_by_parent_id_questions_by_id(self) -> None:
        """Test case for patch_service_surveys_by_parent_id_questions_by_id

        Patch ServiceSurveyQuestion
        """
        pass

    def test_post_service_surveys_by_parent_id_questions(self) -> None:
        """Test case for post_service_surveys_by_parent_id_questions

        Post ServiceSurveyQuestion
        """
        pass

    def test_post_service_surveys_by_parent_id_questions_by_id_copy(self) -> None:
        """Test case for post_service_surveys_by_parent_id_questions_by_id_copy

        Post ServiceSurveyQuestion
        """
        pass

    def test_put_service_surveys_by_parent_id_questions_by_id(self) -> None:
        """Test case for put_service_surveys_by_parent_id_questions_by_id

        Put ServiceSurveyQuestion
        """
        pass


if __name__ == '__main__':
    unittest.main()
