# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.work_types_api import WorkTypesApi


class TestWorkTypesApi(unittest.TestCase):
    """WorkTypesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkTypesApi()

    def tearDown(self) -> None:
        pass

    def test_delete_time_work_types_by_id(self) -> None:
        """Test case for delete_time_work_types_by_id

        Delete WorkType
        """
        pass

    def test_get_time_work_types(self) -> None:
        """Test case for get_time_work_types

        Get List of WorkType
        """
        pass

    def test_get_time_work_types_by_id(self) -> None:
        """Test case for get_time_work_types_by_id

        Get WorkType
        """
        pass

    def test_get_time_work_types_by_id_usages(self) -> None:
        """Test case for get_time_work_types_by_id_usages

        Get List of Usage Count
        """
        pass

    def test_get_time_work_types_by_id_usages_list(self) -> None:
        """Test case for get_time_work_types_by_id_usages_list

        Get List of Usage
        """
        pass

    def test_get_time_work_types_count(self) -> None:
        """Test case for get_time_work_types_count

        Get Count of WorkType
        """
        pass

    def test_patch_time_work_types_by_id(self) -> None:
        """Test case for patch_time_work_types_by_id

        Patch WorkType
        """
        pass

    def test_post_time_work_types(self) -> None:
        """Test case for post_time_work_types

        Post WorkType
        """
        pass

    def test_put_time_work_types_by_id(self) -> None:
        """Test case for put_time_work_types_by_id

        Put WorkType
        """
        pass


if __name__ == '__main__':
    unittest.main()
