# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.board_auto_templates_api import BoardAutoTemplatesApi


class TestBoardAutoTemplatesApi(unittest.TestCase):
    """BoardAutoTemplatesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BoardAutoTemplatesApi()

    def tearDown(self) -> None:
        pass

    def test_delete_service_boards_by_parent_id_auto_templates_by_id(self) -> None:
        """Test case for delete_service_boards_by_parent_id_auto_templates_by_id

        Delete BoardAutoTemplate
        """
        pass

    def test_get_service_boards_by_parent_id_auto_templates(self) -> None:
        """Test case for get_service_boards_by_parent_id_auto_templates

        Get List of BoardAutoTemplate
        """
        pass

    def test_get_service_boards_by_parent_id_auto_templates_by_id(self) -> None:
        """Test case for get_service_boards_by_parent_id_auto_templates_by_id

        Get BoardAutoTemplate
        """
        pass

    def test_get_service_boards_by_parent_id_auto_templates_count(self) -> None:
        """Test case for get_service_boards_by_parent_id_auto_templates_count

        Get Count of BoardAutoTemplate
        """
        pass

    def test_patch_service_boards_by_parent_id_auto_templates_by_id(self) -> None:
        """Test case for patch_service_boards_by_parent_id_auto_templates_by_id

        Patch BoardAutoTemplate
        """
        pass

    def test_post_service_boards_by_parent_id_auto_templates(self) -> None:
        """Test case for post_service_boards_by_parent_id_auto_templates

        Post BoardAutoTemplate
        """
        pass

    def test_put_service_boards_by_parent_id_auto_templates_by_id(self) -> None:
        """Test case for put_service_boards_by_parent_id_auto_templates_by_id

        Put BoardAutoTemplate
        """
        pass


if __name__ == '__main__':
    unittest.main()
