# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.schedule_statuses_api import ScheduleStatusesApi


class TestScheduleStatusesApi(unittest.TestCase):
    """ScheduleStatusesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ScheduleStatusesApi()

    def tearDown(self) -> None:
        pass

    def test_delete_schedule_statuses_by_id(self) -> None:
        """Test case for delete_schedule_statuses_by_id

        Delete ScheduleStatus
        """
        pass

    def test_get_schedule_statuses(self) -> None:
        """Test case for get_schedule_statuses

        Get List of ScheduleStatus
        """
        pass

    def test_get_schedule_statuses_by_id(self) -> None:
        """Test case for get_schedule_statuses_by_id

        Get ScheduleStatus
        """
        pass

    def test_get_schedule_statuses_count(self) -> None:
        """Test case for get_schedule_statuses_count

        Get Count of ScheduleStatus
        """
        pass

    def test_patch_schedule_statuses_by_id(self) -> None:
        """Test case for patch_schedule_statuses_by_id

        Patch ScheduleStatus
        """
        pass

    def test_post_schedule_statuses(self) -> None:
        """Test case for post_schedule_statuses

        Post ScheduleStatus
        """
        pass

    def test_put_schedule_statuses_by_id(self) -> None:
        """Test case for put_schedule_statuses_by_id

        Put ScheduleStatus
        """
        pass


if __name__ == '__main__':
    unittest.main()
