# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from connectwise_psa.models.sales_quota import SalesQuota

class TestSalesQuota(unittest.TestCase):
    """SalesQuota unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SalesQuota:
        """Test SalesQuota
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SalesQuota`
        """
        model = SalesQuota()
        if include_optional:
            return SalesQuota(
                info = {
                    'key' : ''
                    },
                april_margin = 1.337,
                april_revenue = 1.337,
                august_margin = 1.337,
                august_revenue = 1.337,
                category = connectwise_psa.models.product_category_reference.ProductCategoryReference(
                    _info = {
                        'key' : ''
                        }, 
                    id = 56, 
                    name = '', ),
                currency = connectwise_psa.models.currency_reference.CurrencyReference(
                    _info = {
                        'key' : ''
                        }, 
                    currency_code = '', 
                    currency_identifier = '', 
                    decimal_separator = '', 
                    display_id_flag = True, 
                    display_symbol_flag = True, 
                    id = 56, 
                    name = '', 
                    negative_parentheses_flag = True, 
                    number_of_decimals = 56, 
                    right_align = True, 
                    symbol = '', 
                    thousands_separator = '', ),
                december_margin = 1.337,
                december_revenue = 1.337,
                department = connectwise_psa.models.system_department_reference.SystemDepartmentReference(
                    _info = {
                        'key' : ''
                        }, 
                    id = 56, 
                    identifier = '', 
                    name = '', ),
                february_margin = 1.337,
                february_revenue = 1.337,
                forecast_year = 56,
                id = 56,
                january_margin = 1.337,
                january_revenue = 1.337,
                july_margin = 1.337,
                july_revenue = 1.337,
                june_margin = 1.337,
                june_revenue = 1.337,
                location = connectwise_psa.models.system_location_reference.SystemLocationReference(
                    _info = {
                        'key' : ''
                        }, 
                    id = 56, 
                    name = '', ),
                march_margin = 1.337,
                march_revenue = 1.337,
                may_margin = 1.337,
                may_revenue = 1.337,
                member = connectwise_psa.models.member_reference.MemberReference(
                    _info = {
                        'key' : ''
                        }, 
                    id = 56, 
                    identifier = '', 
                    name = '', ),
                november_margin = 1.337,
                november_revenue = 1.337,
                october_margin = 1.337,
                october_revenue = 1.337,
                september_margin = 1.337,
                september_revenue = 1.337,
                sub_category = connectwise_psa.models.product_sub_category_reference.ProductSubCategoryReference(
                    _info = {
                        'key' : ''
                        }, 
                    id = 56, 
                    name = '', )
            )
        else:
            return SalesQuota(
        )
        """

    def testSalesQuota(self):
        """Test SalesQuota"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
