# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.standard_note_infos_api import StandardNoteInfosApi


class TestStandardNoteInfosApi(unittest.TestCase):
    """StandardNoteInfosApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StandardNoteInfosApi()

    def tearDown(self) -> None:
        pass

    def test_get_system_info_standard_notes(self) -> None:
        """Test case for get_system_info_standard_notes

        Get List of StandardNoteInfo
        """
        pass

    def test_get_system_info_standard_notes_by_id(self) -> None:
        """Test case for get_system_info_standard_notes_by_id

        Get StandardNoteInfo
        """
        pass

    def test_get_system_info_standard_notes_count(self) -> None:
        """Test case for get_system_info_standard_notes_count

        Get Count of StandardNoteInfo
        """
        pass


if __name__ == '__main__':
    unittest.main()
