# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.group_infos_api import GroupInfosApi


class TestGroupInfosApi(unittest.TestCase):
    """GroupInfosApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GroupInfosApi()

    def tearDown(self) -> None:
        pass

    def test_get_marketing_groups_by_id_info(self) -> None:
        """Test case for get_marketing_groups_by_id_info

        Get Group Info
        """
        pass

    def test_get_marketing_groups_info(self) -> None:
        """Test case for get_marketing_groups_info

        Get List of GroupInfo
        """
        pass

    def test_get_marketing_groups_info_count(self) -> None:
        """Test case for get_marketing_groups_info_count

        Get Count of Group Info
        """
        pass


if __name__ == '__main__':
    unittest.main()
