# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.taxable_work_role_levels_api import TaxableWorkRoleLevelsApi


class TestTaxableWorkRoleLevelsApi(unittest.TestCase):
    """TaxableWorkRoleLevelsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TaxableWorkRoleLevelsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_finance_tax_codes_by_grandparent_id_work_role_exemptions_by_parent_id_taxable_work_role_levels_by_id(self) -> None:
        """Test case for delete_finance_tax_codes_by_grandparent_id_work_role_exemptions_by_parent_id_taxable_work_role_levels_by_id

        Delete TaxableWorkRoleLevel
        """
        pass

    def test_get_finance_tax_codes_by_grandparent_id_work_role_exemptions_by_parent_id_taxable_work_role_levels(self) -> None:
        """Test case for get_finance_tax_codes_by_grandparent_id_work_role_exemptions_by_parent_id_taxable_work_role_levels

        Get List of TaxableWorkRoleLevel
        """
        pass

    def test_get_finance_tax_codes_by_grandparent_id_work_role_exemptions_by_parent_id_taxable_work_role_levels_by_id(self) -> None:
        """Test case for get_finance_tax_codes_by_grandparent_id_work_role_exemptions_by_parent_id_taxable_work_role_levels_by_id

        Get TaxableWorkRoleLevel
        """
        pass

    def test_get_finance_tax_codes_by_grandparent_id_work_role_exemptions_by_parent_id_taxable_work_role_levels_count(self) -> None:
        """Test case for get_finance_tax_codes_by_grandparent_id_work_role_exemptions_by_parent_id_taxable_work_role_levels_count

        Get Count of TaxableWorkRoleLevel
        """
        pass

    def test_patch_finance_tax_codes_by_grandparent_id_work_role_exemptions_by_parent_id_taxable_work_role_levels_by_id(self) -> None:
        """Test case for patch_finance_tax_codes_by_grandparent_id_work_role_exemptions_by_parent_id_taxable_work_role_levels_by_id

        Patch TaxableWorkRoleLevel
        """
        pass

    def test_post_finance_tax_codes_by_grandparent_id_work_role_exemptions_by_parent_id_taxable_work_role_levels(self) -> None:
        """Test case for post_finance_tax_codes_by_grandparent_id_work_role_exemptions_by_parent_id_taxable_work_role_levels

        Post TaxableWorkRoleLevel
        """
        pass

    def test_put_finance_tax_codes_by_grandparent_id_work_role_exemptions_by_parent_id_taxable_work_role_levels_by_id(self) -> None:
        """Test case for put_finance_tax_codes_by_grandparent_id_work_role_exemptions_by_parent_id_taxable_work_role_levels_by_id

        Put TaxableWorkRoleLevel
        """
        pass


if __name__ == '__main__':
    unittest.main()
