# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.rma_status_notifications_api import RmaStatusNotificationsApi


class TestRmaStatusNotificationsApi(unittest.TestCase):
    """RmaStatusNotificationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RmaStatusNotificationsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_procurement_rma_statuses_by_parent_id_notifications_by_id(self) -> None:
        """Test case for delete_procurement_rma_statuses_by_parent_id_notifications_by_id

        Delete RmaStatusNotification
        """
        pass

    def test_get_procurement_rma_statuses_by_parent_id_notifications(self) -> None:
        """Test case for get_procurement_rma_statuses_by_parent_id_notifications

        Get List of RmaStatusNotification
        """
        pass

    def test_get_procurement_rma_statuses_by_parent_id_notifications_by_id(self) -> None:
        """Test case for get_procurement_rma_statuses_by_parent_id_notifications_by_id

        Get RmaStatusNotification
        """
        pass

    def test_get_procurement_rma_statuses_by_parent_id_notifications_count(self) -> None:
        """Test case for get_procurement_rma_statuses_by_parent_id_notifications_count

        Get Count of RmaStatusNotification
        """
        pass

    def test_patch_procurement_rma_statuses_by_parent_id_notifications_by_id(self) -> None:
        """Test case for patch_procurement_rma_statuses_by_parent_id_notifications_by_id

        Patch RmaStatusNotification
        """
        pass

    def test_post_procurement_rma_statuses_by_parent_id_notifications(self) -> None:
        """Test case for post_procurement_rma_statuses_by_parent_id_notifications

        Post RmaStatusNotification
        """
        pass

    def test_put_procurement_rma_statuses_by_parent_id_notifications_by_id(self) -> None:
        """Test case for put_procurement_rma_statuses_by_parent_id_notifications_by_id

        Put RmaStatusNotification
        """
        pass


if __name__ == '__main__':
    unittest.main()
