# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.tax_code_work_role_exemptions_api import TaxCodeWorkRoleExemptionsApi


class TestTaxCodeWorkRoleExemptionsApi(unittest.TestCase):
    """TaxCodeWorkRoleExemptionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TaxCodeWorkRoleExemptionsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_finance_tax_codes_by_parent_id_work_role_exemptions_by_id(self) -> None:
        """Test case for delete_finance_tax_codes_by_parent_id_work_role_exemptions_by_id

        Delete WorkRoleExemption
        """
        pass

    def test_get_finance_tax_codes_by_parent_id_work_role_exemptions(self) -> None:
        """Test case for get_finance_tax_codes_by_parent_id_work_role_exemptions

        Get List of WorkRoleExemption
        """
        pass

    def test_get_finance_tax_codes_by_parent_id_work_role_exemptions_by_id(self) -> None:
        """Test case for get_finance_tax_codes_by_parent_id_work_role_exemptions_by_id

        Get WorkRoleExemption
        """
        pass

    def test_get_finance_tax_codes_by_parent_id_work_role_exemptions_count(self) -> None:
        """Test case for get_finance_tax_codes_by_parent_id_work_role_exemptions_count

        Get Count of WorkRoleExemption
        """
        pass

    def test_patch_finance_tax_codes_by_parent_id_work_role_exemptions_by_id(self) -> None:
        """Test case for patch_finance_tax_codes_by_parent_id_work_role_exemptions_by_id

        Patch WorkRoleExemption
        """
        pass

    def test_post_finance_tax_codes_by_parent_id_work_role_exemptions(self) -> None:
        """Test case for post_finance_tax_codes_by_parent_id_work_role_exemptions

        Post WorkRoleExemption
        """
        pass

    def test_put_finance_tax_codes_by_parent_id_work_role_exemptions_by_id(self) -> None:
        """Test case for put_finance_tax_codes_by_parent_id_work_role_exemptions_by_id

        Put WorkRoleExemption
        """
        pass


if __name__ == '__main__':
    unittest.main()
