# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.workflow_action_user_defined_fields_api import WorkflowActionUserDefinedFieldsApi


class TestWorkflowActionUserDefinedFieldsApi(unittest.TestCase):
    """WorkflowActionUserDefinedFieldsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkflowActionUserDefinedFieldsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_system_workflows_userdefinedfields_actions_by_parent_id(self) -> None:
        """Test case for delete_system_workflows_userdefinedfields_actions_by_parent_id

        Delete WorkflowActionUserDefinedField
        """
        pass

    def test_get_system_workflows_userdefinedfields_by_grandparent_id_actions_by_parent_id(self) -> None:
        """Test case for get_system_workflows_userdefinedfields_by_grandparent_id_actions_by_parent_id

        Get List of WorkflowActionUserDefinedField
        """
        pass

    def test_patch_system_workflows_userdefinedfields_by_id(self) -> None:
        """Test case for patch_system_workflows_userdefinedfields_by_id

        Patch WorkflowActionUserDefinedField
        """
        pass

    def test_post_system_workflows_userdefinedfields_events_by_grandparent_id(self) -> None:
        """Test case for post_system_workflows_userdefinedfields_events_by_grandparent_id

        Post WorkflowActionUserDefinedField
        """
        pass

    def test_put_system_workflows_userdefinedfields_by_id(self) -> None:
        """Test case for put_system_workflows_userdefinedfields_by_id

        Put WorkflowActionUserDefinedField
        """
        pass


if __name__ == '__main__':
    unittest.main()
