# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.allowed_file_type_api import AllowedFileTypeApi


class TestAllowedFileTypeApi(unittest.TestCase):
    """AllowedFileTypeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AllowedFileTypeApi()

    def tearDown(self) -> None:
        pass

    def test_delete_system_allowedfiletypes_by_id(self) -> None:
        """Test case for delete_system_allowedfiletypes_by_id

        Delete AllowedFileType
        """
        pass

    def test_get_system_allowedfiletypes(self) -> None:
        """Test case for get_system_allowedfiletypes

        Get List of AllowedFileType
        """
        pass

    def test_get_system_allowedfiletypes_by_id(self) -> None:
        """Test case for get_system_allowedfiletypes_by_id

        Get AllowedFileType
        """
        pass

    def test_get_system_allowedfiletypes_count(self) -> None:
        """Test case for get_system_allowedfiletypes_count

        Get Count of AllowedFileType
        """
        pass

    def test_patch_system_allowedfiletypes_by_id(self) -> None:
        """Test case for patch_system_allowedfiletypes_by_id

        Patch AllowedFileType
        """
        pass

    def test_post_system_allowed_file_types(self) -> None:
        """Test case for post_system_allowed_file_types

        Post AllowedFileType
        """
        pass

    def test_put_system_allowedfiletypes_by_id(self) -> None:
        """Test case for put_system_allowedfiletypes_by_id

        Put AllowedFileType
        """
        pass


if __name__ == '__main__':
    unittest.main()
