# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.service_surveys_api import ServiceSurveysApi


class TestServiceSurveysApi(unittest.TestCase):
    """ServiceSurveysApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServiceSurveysApi()

    def tearDown(self) -> None:
        pass

    def test_delete_service_surveys_by_id(self) -> None:
        """Test case for delete_service_surveys_by_id

        Delete ServiceSurvey
        """
        pass

    def test_get_service_surveys(self) -> None:
        """Test case for get_service_surveys

        Get List of ServiceSurvey
        """
        pass

    def test_get_service_surveys_by_id(self) -> None:
        """Test case for get_service_surveys_by_id

        Get ServiceSurvey
        """
        pass

    def test_get_service_surveys_by_id_usages(self) -> None:
        """Test case for get_service_surveys_by_id_usages

        Get List of Usage
        """
        pass

    def test_get_service_surveys_by_id_usages_list(self) -> None:
        """Test case for get_service_surveys_by_id_usages_list

        Get List of Usage
        """
        pass

    def test_get_service_surveys_count(self) -> None:
        """Test case for get_service_surveys_count

        Get Count of ServiceSurvey
        """
        pass

    def test_patch_service_surveys_by_id(self) -> None:
        """Test case for patch_service_surveys_by_id

        Patch ServiceSurvey
        """
        pass

    def test_post_service_surveys(self) -> None:
        """Test case for post_service_surveys

        Post ServiceSurvey
        """
        pass

    def test_post_service_surveys_by_id_copy(self) -> None:
        """Test case for post_service_surveys_by_id_copy

        Post ServiceSurvey
        """
        pass

    def test_put_service_surveys_by_id(self) -> None:
        """Test case for put_service_surveys_by_id

        Put ServiceSurvey
        """
        pass


if __name__ == '__main__':
    unittest.main()
