# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.sla_infos_api import SLAInfosApi


class TestSLAInfosApi(unittest.TestCase):
    """SLAInfosApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SLAInfosApi()

    def tearDown(self) -> None:
        pass

    def test_get_service_slas_by_id_info(self) -> None:
        """Test case for get_service_slas_by_id_info

        Get SLAInfos
        """
        pass

    def test_get_service_slas_info(self) -> None:
        """Test case for get_service_slas_info

        Get List of SLAInfos
        """
        pass

    def test_get_service_slas_info_count(self) -> None:
        """Test case for get_service_slas_info_count

        Get Count of SLAInfos
        """
        pass


if __name__ == '__main__':
    unittest.main()
