# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.configuration_status_infos_api import ConfigurationStatusInfosApi


class TestConfigurationStatusInfosApi(unittest.TestCase):
    """ConfigurationStatusInfosApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConfigurationStatusInfosApi()

    def tearDown(self) -> None:
        pass

    def test_get_company_configurations_statuses_by_id_info(self) -> None:
        """Test case for get_company_configurations_statuses_by_id_info

        Get ConfigurationStatusInfos
        """
        pass

    def test_get_company_configurations_statuses_info(self) -> None:
        """Test case for get_company_configurations_statuses_info

        Get List of ConfigurationStatusInfos
        """
        pass

    def test_get_company_configurations_statuses_info_count(self) -> None:
        """Test case for get_company_configurations_statuses_info_count

        Get Count of ConfigurationStatusInfos
        """
        pass


if __name__ == '__main__':
    unittest.main()
