# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.time_zone_setups_api import TimeZoneSetupsApi


class TestTimeZoneSetupsApi(unittest.TestCase):
    """TimeZoneSetupsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TimeZoneSetupsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_system_time_zone_setups_by_id(self) -> None:
        """Test case for delete_system_time_zone_setups_by_id

        Delete TimeZoneSetup
        """
        pass

    def test_get_system_time_zone_setups(self) -> None:
        """Test case for get_system_time_zone_setups

        Get List of TimeZoneSetup
        """
        pass

    def test_get_system_time_zone_setups_by_id(self) -> None:
        """Test case for get_system_time_zone_setups_by_id

        Get TimeZoneSetup
        """
        pass

    def test_get_system_time_zone_setups_count(self) -> None:
        """Test case for get_system_time_zone_setups_count

        Get Count of TimeZoneSetup
        """
        pass

    def test_patch_system_time_zone_setups_by_id(self) -> None:
        """Test case for patch_system_time_zone_setups_by_id

        Patch TimeZoneSetup
        """
        pass

    def test_post_system_time_zone_setups(self) -> None:
        """Test case for post_system_time_zone_setups

        Post TimeZoneSetup
        """
        pass

    def test_put_system_time_zone_setups_by_id(self) -> None:
        """Test case for put_system_time_zone_setups_by_id

        Put TimeZoneSetup
        """
        pass


if __name__ == '__main__':
    unittest.main()
