# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.purchase_order_line_items_api import PurchaseOrderLineItemsApi


class TestPurchaseOrderLineItemsApi(unittest.TestCase):
    """PurchaseOrderLineItemsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PurchaseOrderLineItemsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_procurement_purchaseorders_by_parent_id_lineitems(self) -> None:
        """Test case for delete_procurement_purchaseorders_by_parent_id_lineitems

        Delete PurchaseOrderLineItem
        """
        pass

    def test_delete_procurement_purchaseorders_by_parent_id_lineitems_bulk(self) -> None:
        """Test case for delete_procurement_purchaseorders_by_parent_id_lineitems_bulk

        Delete BulkResult
        """
        pass

    def test_get_procurement_purchaseorders_by_parent_id_lineitems(self) -> None:
        """Test case for get_procurement_purchaseorders_by_parent_id_lineitems

        Get List of PurchaseOrderLineItem
        """
        pass

    def test_get_procurement_purchaseorders_by_parent_id_lineitems_by_id(self) -> None:
        """Test case for get_procurement_purchaseorders_by_parent_id_lineitems_by_id

        Get PurchaseOrderLineItem
        """
        pass

    def test_get_procurement_purchaseorders_by_parent_id_lineitems_count(self) -> None:
        """Test case for get_procurement_purchaseorders_by_parent_id_lineitems_count

        Get Count of PurchaseOrderLineItem
        """
        pass

    def test_patch_procurement_purchaseorders_by_parent_id_lineitems_by_id(self) -> None:
        """Test case for patch_procurement_purchaseorders_by_parent_id_lineitems_by_id

        Patch PurchaseOrderLineItem
        """
        pass

    def test_post_procurement_purchaseorders_by_parent_id_lineitems(self) -> None:
        """Test case for post_procurement_purchaseorders_by_parent_id_lineitems

        Post PurchaseOrderLineItem
        """
        pass

    def test_post_procurement_purchaseorders_by_parent_id_lineitems_bulk(self) -> None:
        """Test case for post_procurement_purchaseorders_by_parent_id_lineitems_bulk

        Post BulkResult
        """
        pass

    def test_put_procurement_purchaseorders_by_parent_id_lineitems_bulk(self) -> None:
        """Test case for put_procurement_purchaseorders_by_parent_id_lineitems_bulk

        Put BulkResult
        """
        pass

    def test_put_procurement_purchaseorders_by_parent_id_lineitems_by_id(self) -> None:
        """Test case for put_procurement_purchaseorders_by_parent_id_lineitems_by_id

        Put PurchaseOrderLineItem
        """
        pass


if __name__ == '__main__':
    unittest.main()
