# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connectwise_psa.api.communication_type_info_api import CommunicationTypeInfoApi


class TestCommunicationTypeInfoApi(unittest.TestCase):
    """CommunicationTypeInfoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CommunicationTypeInfoApi()

    def tearDown(self) -> None:
        pass

    def test_get_company_communication_types_by_id_info(self) -> None:
        """Test case for get_company_communication_types_by_id_info

        Get CommunicationTypeInfos
        """
        pass

    def test_get_company_communication_types_info(self) -> None:
        """Test case for get_company_communication_types_info

        Get List of CommunicationTypeInfos
        """
        pass

    def test_get_company_communication_types_info_count(self) -> None:
        """Test case for get_company_communication_types_info_count

        Get Count of CommunicationTypeInfos
        """
        pass


if __name__ == '__main__':
    unittest.main()
