# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from connectwise_psa.models.scheduling_member_info import SchedulingMemberInfo

class TestSchedulingMemberInfo(unittest.TestCase):
    """SchedulingMemberInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SchedulingMemberInfo:
        """Test SchedulingMemberInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SchedulingMemberInfo`
        """
        model = SchedulingMemberInfo()
        if include_optional:
            return SchedulingMemberInfo(
                info = {
                    'key' : ''
                    },
                default_email = '',
                first_name = '',
                full_name = '',
                id = 56,
                identifier = '',
                inactive_flag = True,
                last_name = '',
                middle_initial = ''
            )
        else:
            return SchedulingMemberInfo(
        )
        """

    def testSchedulingMemberInfo(self):
        """Test SchedulingMemberInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
