# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictBool, StrictInt, StrictStr, field_validator
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class BillingCycle(BaseModel):
    """
    BillingCycle
    """ # noqa: E501
    info: Optional[Dict[str, StrictStr]] = Field(default=None, alias="_info")
    billing_options: Optional[StrictStr] = Field(alias="billingOptions")
    default_flag: Optional[StrictBool] = Field(default=None, alias="defaultFlag")
    id: Optional[StrictInt] = None
    identifier: StrictStr = Field(description=" Max length: 5;")
    name: StrictStr = Field(description=" Max length: 50;")
    __properties: ClassVar[List[str]] = ["_info", "billingOptions", "defaultFlag", "id", "identifier", "name"]

    @field_validator('billing_options')
    def billing_options_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('BiMonthly', 'BiWeekly', 'Monthly', 'NotRecurring', 'Quarterly', 'SemiAnnual', 'Weekly', 'Yearly'):
            raise ValueError("must be one of enum values ('BiMonthly', 'BiWeekly', 'Monthly', 'NotRecurring', 'Quarterly', 'SemiAnnual', 'Weekly', 'Yearly')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BillingCycle from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if billing_options (nullable) is None
        # and model_fields_set contains the field
        if self.billing_options is None and "billing_options" in self.model_fields_set:
            _dict['billingOptions'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of BillingCycle from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in BillingCycle) in the input: " + _key)

        _obj = cls.model_validate({
            "_info": obj.get("_info"),
            "billingOptions": obj.get("billingOptions"),
            "defaultFlag": obj.get("defaultFlag"),
            "id": obj.get("id"),
            "identifier": obj.get("identifier"),
            "name": obj.get("name")
        })
        return _obj


