# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictBool, StrictInt, StrictStr, field_validator
from pydantic import Field
from connectwise_psa.models.communication_type_reference import CommunicationTypeReference
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ContactCommunication(BaseModel):
    """
    ContactCommunication
    """ # noqa: E501
    info: Optional[Dict[str, StrictStr]] = Field(default=None, alias="_info")
    communication_type: Optional[StrictStr] = Field(default=None, alias="communicationType")
    contact_id: Optional[StrictInt] = Field(default=None, alias="contactId")
    default_flag: Optional[StrictBool] = Field(default=None, alias="defaultFlag")
    domain: Optional[StrictStr] = None
    extension: Optional[StrictStr] = Field(default=None, description=" Max length: 15;")
    id: Optional[StrictInt] = None
    mobile_guid: Optional[StrictStr] = Field(default=None, alias="mobileGuid")
    type: Optional[CommunicationTypeReference] = None
    value: StrictStr = Field(description=" Max length: 250;")
    __properties: ClassVar[List[str]] = ["_info", "communicationType", "contactId", "defaultFlag", "domain", "extension", "id", "mobileGuid", "type", "value"]

    @field_validator('communication_type')
    def communication_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('Email', 'Fax', 'Phone'):
            raise ValueError("must be one of enum values ('Email', 'Fax', 'Phone')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ContactCommunication from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of type
        if self.type:
            _dict['type'] = self.type.to_dict()
        # set to None if communication_type (nullable) is None
        # and model_fields_set contains the field
        if self.communication_type is None and "communication_type" in self.model_fields_set:
            _dict['communicationType'] = None

        # set to None if contact_id (nullable) is None
        # and model_fields_set contains the field
        if self.contact_id is None and "contact_id" in self.model_fields_set:
            _dict['contactId'] = None

        # set to None if default_flag (nullable) is None
        # and model_fields_set contains the field
        if self.default_flag is None and "default_flag" in self.model_fields_set:
            _dict['defaultFlag'] = None

        # set to None if mobile_guid (nullable) is None
        # and model_fields_set contains the field
        if self.mobile_guid is None and "mobile_guid" in self.model_fields_set:
            _dict['mobileGuid'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ContactCommunication from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in ContactCommunication) in the input: " + _key)

        _obj = cls.model_validate({
            "_info": obj.get("_info"),
            "communicationType": obj.get("communicationType"),
            "contactId": obj.get("contactId"),
            "defaultFlag": obj.get("defaultFlag"),
            "domain": obj.get("domain"),
            "extension": obj.get("extension"),
            "id": obj.get("id"),
            "mobileGuid": obj.get("mobileGuid"),
            "type": CommunicationTypeReference.from_dict(obj.get("type")) if obj.get("type") is not None else None,
            "value": obj.get("value")
        })
        return _obj


