# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictBool, StrictInt, StrictStr
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class OpportunityStatus(BaseModel):
    """
    OpportunityStatus
    """ # noqa: E501
    info: Optional[Dict[str, StrictStr]] = Field(default=None, alias="_info")
    closed_flag: Optional[StrictBool] = Field(default=None, alias="closedFlag")
    date_entered: Optional[datetime] = Field(default=None, alias="dateEntered")
    default_flag: Optional[StrictBool] = Field(default=None, alias="defaultFlag")
    entered_by: Optional[StrictStr] = Field(default=None, alias="enteredBy")
    id: Optional[StrictInt] = None
    inactive_flag: Optional[StrictBool] = Field(default=None, alias="inactiveFlag")
    lost_flag: Optional[StrictBool] = Field(default=None, alias="lostFlag")
    name: StrictStr = Field(description=" Max length: 30;")
    won_flag: Optional[StrictBool] = Field(default=None, alias="wonFlag")
    __properties: ClassVar[List[str]] = ["_info", "closedFlag", "dateEntered", "defaultFlag", "enteredBy", "id", "inactiveFlag", "lostFlag", "name", "wonFlag"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OpportunityStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if closed_flag (nullable) is None
        # and model_fields_set contains the field
        if self.closed_flag is None and "closed_flag" in self.model_fields_set:
            _dict['closedFlag'] = None

        # set to None if default_flag (nullable) is None
        # and model_fields_set contains the field
        if self.default_flag is None and "default_flag" in self.model_fields_set:
            _dict['defaultFlag'] = None

        # set to None if inactive_flag (nullable) is None
        # and model_fields_set contains the field
        if self.inactive_flag is None and "inactive_flag" in self.model_fields_set:
            _dict['inactiveFlag'] = None

        # set to None if lost_flag (nullable) is None
        # and model_fields_set contains the field
        if self.lost_flag is None and "lost_flag" in self.model_fields_set:
            _dict['lostFlag'] = None

        # set to None if won_flag (nullable) is None
        # and model_fields_set contains the field
        if self.won_flag is None and "won_flag" in self.model_fields_set:
            _dict['wonFlag'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of OpportunityStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in OpportunityStatus) in the input: " + _key)

        _obj = cls.model_validate({
            "_info": obj.get("_info"),
            "closedFlag": obj.get("closedFlag"),
            "dateEntered": obj.get("dateEntered"),
            "defaultFlag": obj.get("defaultFlag"),
            "enteredBy": obj.get("enteredBy"),
            "id": obj.get("id"),
            "inactiveFlag": obj.get("inactiveFlag"),
            "lostFlag": obj.get("lostFlag"),
            "name": obj.get("name"),
            "wonFlag": obj.get("wonFlag")
        })
        return _obj


