# coding: utf-8

"""
    ConnectWise PSA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2022.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional, Union
from pydantic import BaseModel, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class PricingBreak(BaseModel):
    """
    PricingBreak
    """ # noqa: E501
    info: Optional[Dict[str, StrictStr]] = Field(default=None, alias="_info")
    amount: Optional[Union[StrictFloat, StrictInt]] = None
    detail_id: Optional[StrictInt] = Field(default=None, alias="detailId")
    id: Optional[StrictInt] = None
    price_method: Optional[StrictStr] = Field(alias="priceMethod")
    quantity_end: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="quantityEnd")
    quantity_start: Optional[Union[StrictFloat, StrictInt]] = Field(alias="quantityStart")
    unlimited: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["_info", "amount", "detailId", "id", "priceMethod", "quantityEnd", "quantityStart", "unlimited"]

    @field_validator('price_method')
    def price_method_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('FlatRateForRange', 'PercentMarkupFromCost', 'PercentMarkdownFromPrice', 'PricePerUnit'):
            raise ValueError("must be one of enum values ('FlatRateForRange', 'PercentMarkupFromCost', 'PercentMarkdownFromPrice', 'PricePerUnit')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PricingBreak from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if amount (nullable) is None
        # and model_fields_set contains the field
        if self.amount is None and "amount" in self.model_fields_set:
            _dict['amount'] = None

        # set to None if detail_id (nullable) is None
        # and model_fields_set contains the field
        if self.detail_id is None and "detail_id" in self.model_fields_set:
            _dict['detailId'] = None

        # set to None if price_method (nullable) is None
        # and model_fields_set contains the field
        if self.price_method is None and "price_method" in self.model_fields_set:
            _dict['priceMethod'] = None

        # set to None if quantity_end (nullable) is None
        # and model_fields_set contains the field
        if self.quantity_end is None and "quantity_end" in self.model_fields_set:
            _dict['quantityEnd'] = None

        # set to None if quantity_start (nullable) is None
        # and model_fields_set contains the field
        if self.quantity_start is None and "quantity_start" in self.model_fields_set:
            _dict['quantityStart'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of PricingBreak from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in PricingBreak) in the input: " + _key)

        _obj = cls.model_validate({
            "_info": obj.get("_info"),
            "amount": obj.get("amount"),
            "detailId": obj.get("detailId"),
            "id": obj.get("id"),
            "priceMethod": obj.get("priceMethod"),
            "quantityEnd": obj.get("quantityEnd"),
            "quantityStart": obj.get("quantityStart"),
            "unlimited": obj.get("unlimited")
        })
        return _obj


